vim.schedule(function()
  vim.pack.add({ 'https://github.com/nvim-lua/plenary.nvim' })
  vim.pack.add({ { src = 'https://github.com/theprimeagen/harpoon', version = 'harpoon2' } })

  local harpoon = require('harpoon'):setup()

  vim.keymap.set('n', '<leader>a', function()
    harpoon:list():add()
  end, { desc = 'Harpoon: add file' })
  vim.keymap.set('n', '<C-j>', function()
    harpoon.ui:toggle_quick_menu(harpoon:list())
  end, { desc = 'Harpoon: toggle menu' })
  vim.keymap.set('n', '<C-n>', function()
    harpoon:list():select(1)
  end, { desc = 'Harpoon: select 1st file' })
  vim.keymap.set('n', '<C-e>', function()
    harpoon:list():select(2)
  end, { desc = 'Harpoon: select 2nd file' })
end)
